### ISSUE TITLE
Add wrangler.toml with type

### ISSUE THREAD

**Issue by EverlastingBugstopper** [cloudflare/worker-template-router#15]
In anticipation of https://github.com/cloudflare/wrangler/issues/315

**Comment by victoriabernard92** [comment]
Accidentally just pushed the commit to master 😲sorry! but luckily worked out ok I tested 
https://github.com/cloudflare/worker-template-router/commit/f4c78abd7a07e334b9a1e06e7df9542e42555754

Probably would be a good idea to start branch perms
