### ISSUE TITLE
Is it really necessary to create a Router instance on each request?, I think is not 

### ISSUE THREAD

**Issue by ChStark** [cloudflare/worker-template-router#20]
Reading a little bit the Router code it seams a `Router` instance can be created once upon worker start and then call the `Router#route` method on each event

**Comment by tomByrer** [comment]
For some odd reason, I always assumed there was a new Chromium 'VM' (tab really) instance on every request anyhow?  Or at least could be, since there could be load balancing, re-routing, etc.

**Comment by PierBover** [comment]
@ChStark have you tried that? Does it work?

**Comment by ChStark** [comment]
Yes I took it outside and it still worked

**Comment by signalnerve** [comment]
Closed via #35
