### ISSUE TITLE
What about route params?

### ISSUE THREAD

**Issue by PierBover** [cloudflare/worker-template-router#23]
For example something like: `/users/:userId`

**Comment by nikhiljohn10** [comment]
@PierBover I have been working on it and finally finished it. But I am not able to PR here anything as it seems like this repo is dead. Feel free to check out the [API template](https://github.com/nikhiljohn10/api-worker-template). It is just advanced model of router template.

**Comment by PierBover** [comment]
Thanks @nikhiljohn10 I ended up making my own router.

**Comment by nikhiljohn10** [comment]
> 
> 
> Thanks @nikhiljohn10 I ended up making my own router.
> 
> Check: https://gist.github.com/PierBover/4da745b601d30a6bb850c297b0c0c579
> 
> This is not the final router I'm using but it has route matching and parameters.

It looks very nice. But if you are a fan of MVC, check api template.

**Comment by simplenotezy** [comment]
@nikhiljohn10 Did you by chance also mitigate this issue in your repo? https://github.com/cloudflare/worker-template-router/issues/33

**Comment by signalnerve** [comment]
This should be supported via #35
