### ISSUE TITLE
serverless-cloudflare-workers is an unused dependency

### ISSUE THREAD

**Issue by jahands** [cloudflare/worker-template-router#28]
Why is this included as a dependency when it isn't used? Unless I'm missing something, the code works just fine with it not included.

**Comment by nikhiljohn10** [comment]
That is a true. It have nothing to do with worker code. But I think that it is added as an optional for users who need to use serverless deployment method.

**Comment by jahands** [comment]
Makes sense. I'm new to npm so I was confused but I'm sure experienced users will know they can remove it.
Maybe it should be noted in the readme that it can be removed if you aren't using that deployment method? Especially now that a good alternative exists for deploying to Workers (wrangler).

**Comment by nikhiljohn10** [comment]
i have made an updated version of this template - [API Worker Template](https://github.com/nikhiljohn10/api-worker-template) or you can try more [this one](https://github.com/berstend/tiny-request-router) if you need to use as npm module in wrangler project.

**Comment by jahands** [comment]
Oh hey thanks! The module is actually exactly what I want! I'll go ahead and close this.
