### ISSUE TITLE
typeof r.conditions === 'function', this case is unreachable

### ISSUE THREAD

**Issue by emindeniz99** [cloudflare/worker-template-router#30]
I have tried to write TypeScript types, but I cant find any case that r.conditions are function.       

```
if (typeof r.conditions === 'function') {
        return r.conditions(req)
      } 
```

That block seems unreachable.     

routes array consist of   [Function,Function] or [] (empty array)     

`return this.handle([Trace, Path(url)], handler)`
`return this.handle([], handler)`

**Comment by signalnerve** [comment]
Closed due to rewrite in #35
