### ISSUE TITLE
Demo link not working

### ISSUE THREAD

**Issue by carlsonorozco** [cloudflare/worker-template-router#32]
http://workers-tooling.cf/demos/router/bar

http://workers-tooling.cf/demos/router/foo

**Comment by tadeumaia** [comment]
The url's on the documentation is being report as phishing with Microsoft Edge. Maybe someone from cloudflare should check it out @signalnerve

**Comment by signalnerve** [comment]
> The url's on the documentation is being report as phishing with Microsoft Edge.

oh jeez.

just removed those links, thanks! We don't own that domain and have been trying to scrub it from places over the past few months, thanks for the heads up
