### ISSUE TITLE
needs root route

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/worker-template-router#5]
this template works beautifully with wrangler, however the publish experience could be slightly improved.

when this worker is pushed to a route, wrangler will say "go visit your worker at *defined route*"

however, there is no root route defined in the worker, so the user may see an empty page or something confusing. 

to fix this, let's add a root route that explains the routes that the app designates!

**Comment by linuxjuggler** [comment]
hey @ashleygwilliams can you please check the PR and see if its good to go?

**Comment by ashleygwilliams** [comment]
thank you so much @linuxjuggler !  closed by #10
