### ISSUE TITLE
mention that wrangler can generate and deploy

### ISSUE THREAD

**Issue by ashleygwilliams** [cloudflare/worker-template-router#6]
right now we just say to generate- we probably want to say to generate run this command, and then to publish edit your wrangler.toml and then run wrangler publish

**Comment by linuxjuggler** [comment]
Hey @ashleygwilliams can you check https://github.com/cloudflare/worker-template-router/pull/11 and let me know if it needs any changes.

Thanks

Also, I was wondering if you can point me to where can I report errors in the documentation in this page https://workers.cloudflare.com/docs/tutorials/build-an-application/

**Comment by signalnerve** [comment]
Hey @linuxjuggler - I wrote that tutorial, I'd love your feedback! Want to send me an email? kristian@cloudflare - thanks :)

**Comment by linuxjuggler** [comment]
hey, @signalnerve I'll do right away it's a small changes not so much.

Thanks
